spring.application.name=ClimaAlert

# --- Base de datos ---
spring.datasource.url=jdbc:h2:file:./data/climalert;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- WeatherAPI ---
weatherapi.base-url=https://api.weatherapi.com/v1
weatherapi.api-key=${WEATHERAPI_KEY}
weatherapi.location=-34.6037,-58.3816

# --- Correo (SMTP) ---
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${MAIL_USERNAME}

# --- Destinatarios de alertas ---
alert.email.recipients=alert.email.recipients=admin@clima.com,emergencias@clima.com,meteorologia@clima.com
